// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE0cHOIOXm4sMX596e3Pz7KcNIge1hE-4',
    appId: '1:531884580776:web:6e237e50e6a6b10808c79d',
    messagingSenderId: '531884580776',
    projectId: 'govguide-et',
    authDomain: 'govguide-et.firebaseapp.com',
    storageBucket: 'govguide-et.firebasestorage.app',
    measurementId: 'G-D24KZ2P13Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-RWexdZO0Qir-JDHpEbbFn2jynI304Ag',
    appId: '1:531884580776:android:ac712fd9aebaa9f608c79d',
    messagingSenderId: '531884580776',
    projectId: 'govguide-et',
    storageBucket: 'govguide-et.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Z3KDeUI-8KeIs9d3bZM7HUpghTdNtwQ',
    appId: '1:531884580776:ios:2ffb90e0e5d82ebb08c79d',
    messagingSenderId: '531884580776',
    projectId: 'govguide-et',
    storageBucket: 'govguide-et.firebasestorage.app',
    iosBundleId: 'com.example.govguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Z3KDeUI-8KeIs9d3bZM7HUpghTdNtwQ',
    appId: '1:531884580776:ios:2ffb90e0e5d82ebb08c79d',
    messagingSenderId: '531884580776',
    projectId: 'govguide-et',
    storageBucket: 'govguide-et.firebasestorage.app',
    iosBundleId: 'com.example.govguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE0cHOIOXm4sMX596e3Pz7KcNIge1hE-4',
    appId: '1:531884580776:web:caf18a855e971e2708c79d',
    messagingSenderId: '531884580776',
    projectId: 'govguide-et',
    authDomain: 'govguide-et.firebaseapp.com',
    storageBucket: 'govguide-et.firebasestorage.app',
    measurementId: 'G-E1TGT60G62',
  );
}
